/*
 * The MIT License
 *
 * Copyright 2011 peru.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/*
 * InstancesPanel.java
 *
 * Created on Jan 15, 2011, 8:51:14 AM
 */

package com.yosanai.java.aws.console.panel;

import javax.swing.table.DefaultTableModel;

import com.amazonaws.services.ec2.model.DescribeInstancesResult;
import com.amazonaws.services.ec2.model.Instance;
import com.amazonaws.services.ec2.model.Reservation;
import com.amazonaws.services.ec2.model.Tag;
import com.yosanai.java.aws.console.AWSAware;
import com.yosanai.java.aws.console.AWSConnectionProvider;

/**
 * 
 * @author peru
 */
public class InstancesPanel extends javax.swing.JPanel implements AWSAware {

    protected AWSConnectionProvider awsConnectionProvider;

    /** Creates new form InstancesPanel */
    public InstancesPanel() {
        initComponents();
    }

    public void loadInstances() {
        DefaultTableModel tableModel = (DefaultTableModel) tblInstances.getModel();
        DescribeInstancesResult result = awsConnectionProvider.getConnection().describeInstances();
        while (0 < tableModel.getRowCount()) {
            tableModel.removeRow(0);
        }
        for (Reservation reservation : result.getReservations()) {
            for (Instance instance : reservation.getInstances()) {
                StringBuilder tags = new StringBuilder();
                for (Tag tag : instance.getTags()) {
                    tags.append(tag.getKey());
                    tags.append("=");
                    tags.append(tag.getValue());
                }
                tableModel.addRow(new Object[] { instance.getInstanceId(), instance.getPublicDnsName(),
                        instance.getPrivateDnsName(), instance.getPublicIpAddress(), instance.getState().getName(),
                        tags.toString() });
            }
        }
    }

    /*
     * (non-Jsdoc)
     * 
     * @see com.yosanai.java.aws.console.AWSAware#init()
     */
    @Override
    public void init() {
        loadInstances();
    }

    /*
     * (non-Jsdoc)
     * 
     * @see
     * com.yosanai.java.aws.console.AWSAware#setAwsConnectionProvider(com.yosanai
     * .java.aws.console.AWSConnectionProvider)
     */
    @Override
    public void setAwsConnectionProvider(AWSConnectionProvider awsConnectionProvider) {
        this.awsConnectionProvider = awsConnectionProvider;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInstances = new javax.swing.JPanel();
        scrInstances = new javax.swing.JScrollPane();
        tblInstances = new javax.swing.JTable();
        ponlInstanceMain = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnlInstances.setLayout(new java.awt.BorderLayout());

        tblInstances.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

        }, new String[] { "Instance ID", "Public DNS", "Private DNS", "Private IP", "State", "Tag" }) {
            Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class, java.lang.String.class };

            boolean[] canEdit = new boolean[] { false, false, false, false, false, false };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblInstances.setColumnSelectionAllowed(true);
        scrInstances.setViewportView(tblInstances);

        pnlInstances.add(scrInstances, java.awt.BorderLayout.CENTER);

        ponlInstanceMain.setLayout(new java.awt.BorderLayout());

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        ponlInstanceMain.add(btnRefresh, java.awt.BorderLayout.CENTER);

        pnlInstances.add(ponlInstanceMain, java.awt.BorderLayout.PAGE_START);

        add(pnlInstances, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnRefreshActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;

    private javax.swing.JPanel pnlInstances;

    private javax.swing.JPanel ponlInstanceMain;

    private javax.swing.JScrollPane scrInstances;

    private javax.swing.JTable tblInstances;
    // End of variables declaration//GEN-END:variables

}
