/*
 * The MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package com.yosanai.java.aws.console;

/**
 * 
 * @author Saravana Perumal Shanmugam
 */
public class MainAWSPanel extends javax.swing.JPanel implements AWSAware {

    protected AWSConnectionProvider awsConnectionProvider;

    /** Creates new form MainAWSPanel */
    public MainAWSPanel() {
        initComponents();
    }

    /**
     * @param awsConnectionProvider
     *            the awsConnectionProvider to set
     */
    public void setAwsConnectionProvider(AWSConnectionProvider awsConnectionProvider) {
        this.awsConnectionProvider = awsConnectionProvider;
        instancesPanel.setAwsConnectionProvider(awsConnectionProvider);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        instancesPanel = new com.yosanai.java.aws.console.panel.InstancesPanel();

        setLayout(new java.awt.BorderLayout());

        tabMain.addTab("Instances", instancesPanel);

        add(tabMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshActionPerformed
    }// GEN-LAST:event_btnRefreshActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.yosanai.java.aws.console.panel.InstancesPanel instancesPanel;

    private javax.swing.JTabbedPane tabMain;

    // End of variables declaration//GEN-END:variables

    /*
     * (non-Jsdoc)
     * 
     * @see com.yosanai.java.aws.console.AWSAware#init()
     */
    @Override
    public void init() {
        instancesPanel.init();
    }

}
